- 👋 Hi, I’m @SUMIT-JADHAV-23
- 👀 I’m interested in Data science
- 📫 I,m seeking for opportunity
- 🌱 I’m currently learning Data science,Data analysis,python,tableau,SQL
- 💞️ I’m looking to collaborate with skill set
- 📫 How to reach me Mail : s.v.jadhavjob@gmail.com
